      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subheading", name: "subheading", widget: "string", required: false }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Description", name: "description", widget: "text" }

          # INTRO
          - label: "Intro"
            name: "intro"
            widget: "object"
            fields:
              - label: "Blurbs"
                name: "blurbs"
                widget: "list"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Text", name: "text", widget: "text" }

          # MAIN SECTION
          - label: "Main Section"
            name: "main"
            widget: "object"
            fields:
              - { label: "Heading", name: "heading", widget: "string", required: false }
              - { label: "Description", name: "description", widget: "text", required: false }

              - label: "Image 1"
                name: "image1"
                widget: "object"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Alt", name: "alt", widget: "string" }

              - label: "Image 2"
                name: "image2"
                widget: "object"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Alt", name: "alt", widget: "string" }
